### ISSUE TITLE
Design and implement the End block to correctly terminate workflows.

### ISSUE THREAD

**Issue by c0rtexR** [softflow24/data-river#11]
### Subtask: Design and implement the End block to correctly terminate workflows.

**Task Overview**: Develop the **End block** that will terminate workflows in the **data-river** system. The End block will signal the completion of a workflow and ensure that any final output data is properly handled.

**Specific 🎯**: 
- Design the End block to serve as the termination point of the workflow, ensuring it stops execution once it is reached.
- Implement the capability for the End block to handle final output data, supporting core types (`bool`, `number`, `string`), and subtypes like JSON if necessary.
- Ensure the block provides a way to finalize the workflow, such as passing outputs to logs or external systems if needed.

**Measurable 📏**: The End block should terminate the workflow when reached in the flow. It should handle output data correctly, whether it's a simple type or a subtype like JSON. Unit tests will confirm that workflows are properly finalized and outputs are handled without errors.

**Achievable 🚀**: This task is achievable by extending the base class and focusing on finalizing workflows. It will use common methods like `execute()` and `validate()` while implementing specific logic for terminating workflows.

**Relevant 🎯**: The End block is critical as it signals the conclusion of a workflow, ensuring data is processed and the workflow is finalized correctly.

**Time-bound ⏳**: This task should be completed within 3 days to ensure the proper termination functionality is in place before full workflow testing.

**Acceptance Criteria ✅**:
- [x] The End block correctly terminates workflows when reached.
- [x] It handles output data of core types (`bool`, `number`, `string`, with subtypes like JSON).
- [ ] Unit tests for the End block pass, verifying termination functionality and data handling.
- [x] The End block integrates seamlessly into the flow editor UI.

**Comment by iploooox** [comment]
Updated status, looks like only tests are missing.

![Image](https://github.com/user-attachments/assets/9c70a13f-ac2d-4fed-a9fa-48d267415cdb)


```json
{
  "result": {
    "0": {
      "nodeType": "blocks/start@0.1",
      "nodeId": "1",
      "outputs": {
        "started": true
      },
      "inputs": {}
    },
    "1": {
      "nodeType": "blocks/input@0.1",
      "nodeId": "2",
      "outputs": {
        "data": "test"
      },
      "inputs": {
        "input": "test"
      }
    },
    "2": {
      "nodeType": "blocks/output@0.1",
      "nodeId": "3",
      "outputs": {
        "data": "test"
      },
      "inputs": {
        "data": "test"
      }
    },
    "3": {
      "nodeType": "blocks/end@0.1",
      "nodeId": "4",
      "outputs": {},
      "inputs": {
        "data": "test"
      }
    }
  },
  "errors": {}
}
```

**Comment by girl-loves-coding** [comment]
I suggest we close it and add tests later to clean the board a bit. @c0rtexR  what do you think?

**Comment by c0rtexR** [comment]
done we will skip tests for now
