### ISSUE TITLE
[Task] - Implement Theme Toggle (Dark/Light/System) in Navbar

### ISSUE THREAD

**Issue by c0rtexR** [softflow24/data-river#137]
## Task Overview

Implement a theme toggle in the top-right corner of the navbar to switch between dark, light, and system themes in data-river. The toggle should display an icon based on the current theme and use Shadcn's button and dropdown-menu components. User selections should update both a cookie and the Redux state.

## SMART Criteria

- **Specific** 🎯
  - Add a theme toggle button to the navbar using Shadcn's button component.
  - The button should display an icon representing the current theme.
  - On click, the button opens a dropdown menu (using Shadcn's dropdown-menu component) with options: Dark, Light, System.
  - When a user selects an option, update the cookie and Redux state to reflect the chosen theme.
  - Adjust the layout in the Remix client to use the cookie value instead of system preference.

- **Measurable** 📏
  - The theme toggle button is visible and functional in the navbar.
  - Selecting a theme updates the UI accordingly.
  - The user's theme preference persists across sessions via the cookie.
  - The Redux state reflects the current theme.

- **Achievable** 🚀
  - Utilize Shadcn's components and lucide-react icons.
  - Follow provided code examples to manage cookies and state updates.
  - Adjust existing `useEffect` in the Remix client.

- **Relevant** 🎯
  - Enhances user experience by allowing theme customization.
  - Aligns with the goal of making the UI adaptable and user-friendly.

- **Time-bound** ⏳
  - Complete the implementation within 2 days.

## Subtasks 📝

- [ ] Add a theme toggle button to the navbar using Shadcn's button component.
- [ ] Display the appropriate icon based on the current theme (suggestions below).
- [ ] Implement the dropdown menu with options: Dark, Light, System.
- [ ] Update the cookie and Redux state when a theme is selected.
- [ ] Adjust the Remix client's layout to use the cookie value for the theme.
- [ ] Write a fetcher to handle theme changes if necessary.
- [ ] Test the theme toggle functionality across different browsers and sessions.

## Acceptance Criteria ✅

- [ ] Theme toggle button is present in the navbar and displays the correct icon.
- [ ] Clicking the button opens a dropdown with Dark, Light, and System options.
- [ ] Selecting a theme updates the UI immediately.
- [ ] User's theme preference persists via a cookie.
- [ ] Redux state accurately reflects the current theme.
- [ ] Layout in Remix client uses the cookie value for theme preference.

## Additional Notes 🗒

- **Icon Suggestions (using lucide-react):**
  - **Light Theme**: `Sun`
  - **Dark Theme**: `Moon`
  - **System Theme**: `Monitor` or `Laptop`

- **Example Code for Updating Cookie:**

  ```javascript
  const onThemeChange = React.useCallback((theme) => {
    setTheme(theme);
    document.cookie = `THEME_PREFERENCE=${theme}; path=/; max-age=${60 * 60 * 24 * 365}`;
  }, []);
  ```

- **Adjusting Remix Client Layout:**

  Update the `useEffect` in `root.tsx` to read the theme from the cookie and apply the correct class to Tailwind:

  ```javascript
  useEffect(() => {
    const theme = getCookie('THEME_PREFERENCE') || 'system';

    if (theme === 'dark' || (theme === 'system' && window.matchMedia("(prefers-color-scheme: dark)").matches)) {
      document.documentElement.classList.add("dark");
    } else {
      document.documentElement.classList.remove("dark");
    }

    const mediaQuery = window.matchMedia("(prefers-color-scheme: dark)");
    const handleChange = (e) => {
      if (e.matches && theme === 'system') {
        document.documentElement.classList.add("dark");
      } else if (!e.matches && theme === 'system') {
        document.documentElement.classList.remove("dark");
      }
    };

    mediaQuery.addEventListener("change", handleChange);
    
    return () => {
      mediaQuery.removeEventListener("change", handleChange);
    };
  }, []);
  ```

- **Example Fetcher for Theme Changes:**

  ```javascript
  const fetcher = useFetcher();

  const onThemeSelect = (theme) => {
    fetcher.submit({ theme }, { method: 'post', action: '/api/theme' });
    // Update state and cookie as well
  };
  ```

  In your `routes/api/theme.tsx`, handle the POST request to update the theme preference.

  ```javascript
  export const action = async ({ request }) => {
    const formData = await request.formData();
    const theme = formData.get('theme') || 'system';

    // Set cookie header
    return json(
      { success: true },
      {
        headers: {
          'Set-Cookie': `THEME_PREFERENCE=${theme}; Path=/; Max-Age=${60 * 60 * 24 * 365}`,
        },
      }
    );
  };
  ```

- **Resource**:
  Use [Shadcn's dropdown-menu component](https://ui.shadcn.com/docs/components/dropdown-menu) for the context menu and theme toggle.

[Use effect](https://github.com/softflow24/data-river/blob/main/packages/client/app/root.tsx#L43-L68) manimulating css classes for theme
