### ISSUE TITLE
Define the node configuration structure (ID-based with input/output keys and task-specific settings).

### ISSUE THREAD

**Issue by c0rtexR** [softflow24/data-river#37]
### **Subtask: Define the node configuration structure (ID-based with input/output keys and task-specific settings)**

---

**Task Overview**:  
Develop a **node configuration structure** where each node has a unique **ID** and includes **input/output keys** to define data flow between nodes. Additionally, nodes will have **task-specific settings** (e.g., REST API details, conditional logic) to allow for dynamic configuration.

---

### **SMART Criteria**

**Specific 🎯**:  
Define the node configuration structure that includes:
- A unique **ID** for each node, ensuring it can be referenced in the workflow.
- **Input and output keys** to manage the flow of data between nodes.
- **Task-specific settings** to configure node behavior (e.g., API method, URL, condition handling, etc.).
- Include error handling and optional configurations for more complex tasks.

**Measurable 📏**:  
Success will be measured by:
- Each node having a well-defined structure that includes **ID**, **input/output keys**, and **task settings**.
- The configuration being tested in a sample workflow with at least **5 nodes** to ensure functionality and clarity.
- Positive feedback from **90% of developers** using the configuration.

**Achievable 🚀**:  
This task is achievable using standard JavaScript objects or JSON schema to structure the configuration, ensuring that each node is fully configurable and can pass data between other nodes.

**Relevant 🎯**:  
Defining the node configuration is a critical step for ensuring that workflows in the **data-river editor** are modular, scalable, and flexible.

**Time-bound ⏳**:  
This task should be completed within **1 week** to allow sufficient time for testing the configuration in more complex workflows.

---

### **Subtasks 📝**  
- [x] Design the base **node structure** that includes **ID**, **input keys**, **output keys**, and **task-specific settings**.
- [x] Include **optional settings** like error handling, retries, or conditions for more complex nodes.
- [x] Ensure each node can connect and communicate with other nodes via input/output keys.
- [ ] Test the configuration in a small workflow with at least **5 nodes** to verify data flow and task configuration.
- [ ] Refine the structure based on developer feedback and testing results.

---

### **Acceptance Criteria ✅**  
- [x] Each node has a clearly defined structure with **ID**, **input/output keys**, and **task settings**.
- [ ] The node configuration is successfully tested in a **5-node workflow**, and all nodes pass values as expected.
- [ ] Positive feedback from **90% of developers** using the configuration in test workflows.

---

### **Additional Notes 🗒**  
- Ensure that the structure is flexible enough to handle future expansion (e.g., adding more node types or task-specific configurations).

**Comment by iploooox** [comment]
Seems like we got this covered, just need tests and perhaps 2 outputs with logic node?

UI:
```ts
import Icons from "lucide-react";

interface Control {
  type: "text" | "text-area";
  label: string;
  name: string;
  placeholder?: string;
}

export interface NodeData {
  block: string;
  label: string;
  description?: string;
  color: string;
  sourceHandle: boolean;
  targetHandle: boolean;
  icon: keyof typeof Icons;
  controls?: Control[];
  inputs?: Record<string, unknown>;
  outputs?: Record<string, unknown>;
}

```

Engine:
```ts
export interface IBlockConfig {
  id: string;
  type: string;
  inputConfigs?: Record<string, { type: string; required: boolean }>;
  outputConfigs?: Record<string, { type: string }>;
  inputs?: Record<string, unknown>;
  retry?: number;
  timeout?: number;
  onError?: (error: Error, blockConfig: IBlockConfig) => void;
}

export interface IConnection {
  from: string;
  to: string;
  inputKey: string;
  outputKey: string;
}

export interface IExecutionEngineConfig {
  workflowConfig: IWorkflowConfig;
  environment: IEnvironment;
  maxConcurrentTasks: number;
  retryOnFailure: boolean;
  supportsWebSocket: boolean;
}

export interface IWorkflowConfig {
  maxConcurrentTasks: number;
  supportsWebSocket: boolean;
  executionContext: "browser" | "server";
  retryOnFailure?: boolean;
  continueOnError?: boolean;
  connections: IConnection[];
}
```

**Comment by c0rtexR** [comment]
done we will skip tests for now
