### ISSUE TITLE
Implement a system for passing values between nodes via their configuration.

### ISSUE THREAD

**Issue by c0rtexR** [softflow24/data-river#38]
### **Subtask: Implement a system for passing values between nodes via their configuration**

---

**Task Overview**:  
Develop a system that allows **values to be passed** between nodes based on their **input/output keys** and configuration settings. The system will manage how data flows from one node to the next, ensuring that each node processes its inputs and generates the correct outputs for downstream nodes.

---

### **SMART Criteria**

**Specific 🎯**:  
Implement a system that:
- Allows **nodes to receive values** through input keys and **pass values** to the next node using output keys.
- Ensures that values are passed dynamically based on the node’s configuration and the overall workflow setup.
- Supports complex configurations, such as **multiple input/output connections**, conditional flows, and optional settings.

**Measurable 📏**:  
Success will be measured by:
- Values being correctly passed between nodes in a **5-node workflow**, with each node receiving and processing data according to its configuration.
- Positive feedback from **90% of developers** testing the system, confirming that value passing works smoothly.

**Achievable 🚀**:  
This task is achievable by using JavaScript objects to model the workflow configuration and implementing logic that handles the data flow between nodes, possibly using **event-driven** or **callback-based** systems to trigger node executions.

**Relevant 🎯**:  
This system is essential for making the **data-river editor** functional, as it ensures that nodes can communicate effectively and perform tasks based on the flow of data.

**Time-bound ⏳**:  
This task should be completed within **2 weeks** to ensure time for testing in various workflow configurations.

---

### **Subtasks 📝**  
- [x] Create a system to **capture input values** for each node from the preceding node’s output.
- [x] Implement the logic for **passing values** from one node to the next based on **input/output keys**.
- [ ] Ensure compatibility with multiple input/output connections, and handle complex nodes such as **conditional flows** or **parallel execution**.
- [ ] Test the system with a small workflow to ensure data is passed accurately between nodes.
- [ ] Gather feedback from developers to refine the system based on their experience with passing values between nodes.

---

### **Acceptance Criteria ✅**  
- [x] Values are successfully passed between nodes in a **5-node workflow**, with all nodes receiving and processing their inputs as expected.
- [ ] Positive feedback from **90% of developers** indicates that the system works as intended, with smooth data flow.
- [ ] Testing shows that the system handles **multiple inputs/outputs** and complex conditions.

---

### **Additional Notes 🗒**  
Ensure the system is flexible enough to handle future additions, such as more complex nodes or advanced workflow configurations.

**Comment by iploooox** [comment]
So far it seems to work, we need multiple input, output scenario and then tests to complete this.

```ts
const connections: IConnection[] = edges.map((edge) => ({
      from: edge.source,
      to: edge.target,
      inputKey: "data",
      outputKey: "data",
    }));
```

```json
{
  "result": {
    "0": {
      "nodeType": "blocks/start@0.1",
      "nodeId": "1",
      "outputs": {
        "started": true
      },
      "inputs": {}
    },
    "1": {
      "nodeType": "blocks/input@0.1",
      "nodeId": "2",
      "outputs": {
        "data": "123"
      },
      "inputs": {
        "input": "123"
      }
    },
    "2": {
      "nodeType": "blocks/output@0.1",
      "nodeId": "3",
      "outputs": {
        "data": "123"
      },
      "inputs": {
        "data": "123"
      }
    },
    "3": {
      "nodeType": "blocks/end@0.1",
      "nodeId": "4",
      "outputs": {},
      "inputs": {
        "data": "123"
      }
    }
  },
  "errors": {}
}
```

**Comment by c0rtexR** [comment]
done we will skip tests for now
